#!/bin/sh
set -e

case "$1" in
    remove)
        rm -rf /usr/share/zabbix/ui/modules/radar-chart 2>/dev/null || true
        rm -rf /usr/share/zabbix/modules/radar-chart 2>/dev/null || true
        ;;
esac

#DEBHELPER#

exit 0
